<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\jaytwo.SuperDelete\jaytwo.SuperDelete.csproj" />
    <PackageReference Include="jaytwo.RuntimeRevelation" Version="0.2.0" />
  </ItemGroup>

</Project>
